# Generated by Django 5.1.1 on 2025-03-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0002_alter_article_author_alter_article_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Publication Date"
            ),
        ),
    ]
